# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ahmet/Desktop/yazlab1.2/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 1003)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 50, 41, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 91, 21))
        self.label.setObjectName("label")
        self.Birsutungoster = QtWidgets.QPushButton(self.centralwidget)
        self.Birsutungoster.setGeometry(QtCore.QRect(90, 80, 411, 28))
        self.Birsutungoster.setObjectName("Birsutungoster")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 221, 16))
        self.label_2.setObjectName("label_2")
        self.threadsayisi = QtWidgets.QLineEdit(self.centralwidget)
        self.threadsayisi.setGeometry(QtCore.QRect(230, 10, 41, 22))
        self.threadsayisi.setObjectName("threadsayisi")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 181, 16))
        self.label_3.setObjectName("label_3")
        self.sutunsec = QtWidgets.QLineEdit(self.centralwidget)
        self.sutunsec.setGeometry(QtCore.QRect(190, 50, 61, 22))
        self.sutunsec.setObjectName("sutunsec")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 170, 111, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 170, 81, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.ayni1sutungoster = QtWidgets.QPushButton(self.centralwidget)
        self.ayni1sutungoster.setGeometry(QtCore.QRect(200, 170, 93, 28))
        self.ayni1sutungoster.setObjectName("ayni1sutungoster")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 170, 111, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 180, 81, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.ayni2sutungoster = QtWidgets.QPushButton(self.centralwidget)
        self.ayni2sutungoster.setGeometry(QtCore.QRect(500, 170, 93, 28))
        self.ayni2sutungoster.setObjectName("ayni2sutungoster")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 130, 161, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 130, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 130, 91, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(400, 130, 41, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 81, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 230, 51, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 230, 111, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(330, 230, 111, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.complaintidgetir = QtWidgets.QPushButton(self.centralwidget)
        self.complaintidgetir.setGeometry(QtCore.QRect(120, 260, 411, 28))
        self.complaintidgetir.setObjectName("complaintidgetir")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 310, 81, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(80, 310, 51, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 310, 111, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(300, 310, 111, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.zipcodegetir = QtWidgets.QPushButton(self.centralwidget)
        self.zipcodegetir.setGeometry(QtCore.QRect(110, 340, 421, 28))
        self.zipcodegetir.setObjectName("zipcodegetir")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(460, 230, 91, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(560, 230, 41, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(430, 310, 91, 21))
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(540, 310, 41, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(105, 421, 401, 351))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projem"))
        self.label.setText(_translate("MainWindow", "Benzerlik Oranı"))
        self.Birsutungoster.setText(_translate("MainWindow", "Girilen Sütuna Ait Benzerlik Oranına Eşit Ve Büyük Kayıtları Göster"))
        self.label_2.setText(_translate("MainWindow", "  Kaç Thread Kullanmak İstiyorsunuz?"))
        self.label_3.setText(_translate("MainWindow", "İşlem Yapmak İstediğiniz Sütun"))
        self.label_4.setText(_translate("MainWindow", "Gösterilecek Sütun"))
        self.ayni1sutungoster.setText(_translate("MainWindow", "1 Sütun Göster"))
        self.label_5.setText(_translate("MainWindow", "Gösterilecek Sütun"))
        self.ayni2sutungoster.setText(_translate("MainWindow", "2 Sütun Göster"))
        self.label_6.setText(_translate("MainWindow", "Benzerliği Aranacak Sütun"))
        self.label_7.setText(_translate("MainWindow", "Benzerlik Oranı"))
        self.label_8.setText(_translate("MainWindow", "Complaint ID"))
        self.label_9.setText(_translate("MainWindow", "Gösterilecek Sütun"))
        self.complaintidgetir.setText(_translate("MainWindow", "Girilen Sütunda Complaint ID\'leri Aynı Olan Kayıtları Göster"))
        self.label_10.setText(_translate("MainWindow", "Zıp Code"))
        self.label_11.setText(_translate("MainWindow", "Gösterilecek Sütun"))
        self.zipcodegetir.setText(_translate("MainWindow", "Girilen Sütunda Zıp Code\'ları Aynı Olan Kayıtları Göster"))
        self.label_12.setText(_translate("MainWindow", "Benzerlik Oranı"))
        self.label_13.setText(_translate("MainWindow", "Benzerlik Oranı"))

